apiVersion: v1
kind: Namespace
metadata:
  name: app1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-app
  namespace: app1
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app1
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app1
    spec:
      containers:
      - image: 975635808270.dkr.ecr.us-west-2.amazonaws.com/node:latest
        imagePullPolicy: Always
        name: app1
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: 3000
    external-dns.alpha.kubernetes.io/hostname: service-app01.yourdomain.cloud
    alb.ingress.kubernetes.io/target-type: instance
    kubernetes.io/ingress.class: alb
  name: service-app
  namespace: app1
spec:
  type: LoadBalancer
  ports:
    - port: 3000
  selector:
    app.kubernetes.io/name: app1
