apiVersion: v1
kind: Namespace
metadata:
  name: app1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-app
  namespace: app1
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app1
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app1
    spec:
      containers:
      - image: 975635808270.dkr.ecr.us-west-2.amazonaws.com/node:latest
        imagePullPolicy: Always
        name: app1
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: service-app
  namespace: app1
spec:
  type: LoadBalancer
  ports:
    - port: 3000
#       targetPort: 3000
#       protocol: TCP
#   type: NodePort
#   selector:
#     app.kubernetes.io/name: app
